version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: proyecto_utp
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
  app:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
